### ISSUE TITLE
Licensing and contribution challenge

### ISSUE THREAD

**Issue by adulau** [elastic/protections-artifacts#4]
Thanks a lot for the initiative, that's great but I have two points which could be improved to help a wider contribution and sharing of those rules.

- Using an approved Open Source license for this repository;
- Removing the requirements of the CLA on this repository;

As open source developers (in this case [MISP](https://github.com/MISP)), we are always looking for useful content such as detection rules to be included by default in the MISP open source distribution. With the current licensing, it won't be possible to include your useful `protections-artifacts` rules set.

**Comment by joe-desimone** [comment]
Thank you for your thoughtful feedback @adulau. This [blog post](https://www.elastic.co/blog/elastic-license-v2) explains our rationale for choosing the elastic license. While this has been our decision today, I appreciate feedback such as yours for future consideration.

**Comment by adulau** [comment]
As you recently [changed the license of Elasticsearch to AGPL](https://ir.elastic.co/news/news-details/2024/Elastic-Announces-Open-Source-License-for-Elasticsearch-and-Kibana-Source-Code/default.aspx), this might be a good opportunity to revert the license terms for the rules before you once again face significant community-driven competition, which could become an issue.

**Comment by Neo23x0** [comment]
This tweet describes my issues with the Elastic license 

https://x.com/cyb3rops/status/1910347566388031587

**Comment by pombredanne** [comment]
gentle ping, using the AGPL, the GPL or any other OSI-approved license would be an awesome thing!
