### ISSUE TITLE
[Update behavior]: Do older elastic endpoint security protection versions receive rule updates?

### ISSUE THREAD

**Issue by Liblor** [elastic/protections-artifacts#8]
Hello

I have a question regarding protection-artifacts update procedure. In particular, when an older elastic-agent version is used.
As far as I gathered, the endpoint security protection downloads the artifact-x.x.x.zip which contains the manifest.json which specifies the  rules which should be fetched. Now, I was wondering, if a client still receives the rule/signature updates even when not the newest elastic-agent version is used, i.e will artifact-8.4.3.zip be updated once protections-artifacts receives a update?

**Comment by joe-desimone** [comment]
Good question. In general, yes all supported agent/endpoint versions will continue to receive updates.

However, there is some nuiance. For example, occasionally we add new rules that take advantage of new features of agent/endpoint. These have an effective minimum agent/endpoint versions. 

We will add this piece of metadata to this repo so it is clear which versions are supported by each rule.

**Comment by Liblor** [comment]
Thanks! That sounds good, I look forward to the added metadata.
